// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAli0wteOFIDmjBNkDseVTpckLFaWx1vpQ',
    appId: '1:457559453959:web:d9157ddc71394933b115a2',
    messagingSenderId: '457559453959',
    projectId: 'medical-tracking-app',
    authDomain: 'medical-tracking-app.firebaseapp.com',
    storageBucket: 'medical-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gZd6YSatdNomxwQaX1NJ0BYXWOohp-g',
    appId: '1:457559453959:android:6d54526ca2309952b115a2',
    messagingSenderId: '457559453959',
    projectId: 'medical-tracking-app',
    storageBucket: 'medical-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_LcVPjESYr8jx7EKmnnsz2Bt-i3uZko',
    appId: '1:457559453959:ios:dbfbf150b4f8ee2fb115a2',
    messagingSenderId: '457559453959',
    projectId: 'medical-tracking-app',
    storageBucket: 'medical-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.medicalTrackingApp',
  );
}
