// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsbg7p5S6-CFzk3p5bEulME29GD8hefmc',
    appId: '1:835225532599:web:1afd54ea93628a7312b532',
    messagingSenderId: '835225532599',
    projectId: 'auth-453b4',
    authDomain: 'auth-453b4.firebaseapp.com',
    storageBucket: 'auth-453b4.firebasestorage.app',
    measurementId: 'G-2R1CZKP2DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE4EkDZs4KPdha-pXeYLgCkJwlic9wyOs',
    appId: '1:835225532599:android:c257bd2b9665e6ca12b532',
    messagingSenderId: '835225532599',
    projectId: 'auth-453b4',
    storageBucket: 'auth-453b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Da8gSEY81fprwNkgqMBMFKoE5EImJ8U',
    appId: '1:835225532599:ios:e5bfb1527b9e890512b532',
    messagingSenderId: '835225532599',
    projectId: 'auth-453b4',
    storageBucket: 'auth-453b4.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Da8gSEY81fprwNkgqMBMFKoE5EImJ8U',
    appId: '1:835225532599:ios:e5bfb1527b9e890512b532',
    messagingSenderId: '835225532599',
    projectId: 'auth-453b4',
    storageBucket: 'auth-453b4.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsbg7p5S6-CFzk3p5bEulME29GD8hefmc',
    appId: '1:835225532599:web:13d05ada429f089312b532',
    messagingSenderId: '835225532599',
    projectId: 'auth-453b4',
    authDomain: 'auth-453b4.firebaseapp.com',
    storageBucket: 'auth-453b4.firebasestorage.app',
    measurementId: 'G-ND8NLP206D',
  );
}
